sonar.projectKey=sales-service
sonar.projectName=lab-sales-service
sonar.sources=sales-service/src/main
sonar.java.binaries=sales-service/target/classes
sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/*.spec.ts
sonar.qualitygate.wait=true
# For SonarQube Cloud uncomment and set:
# sonar.organization=REPLACE_ORGANIZATION
