replicaCount: 2

image:
  repository: 629690103043.dkr.ecr.us-east-1.amazonaws.com/sales-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8082
  targetPort: 8082

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

strategy:
  maxUnavailable: 0
  maxSurge: 1

env: []
podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

